import { ObjectId } from "mongodb";

export type Address = {
  id: string; // Typically a UUID string generated by frontend
  type: "shipping" | "billing";
  recipientName: string;
  street: string;
  city: string;
  state: string;
  zip: string;
  country: string;
  isDefault: boolean;
};

export type PaymentMethod = {
  id: string;
  provider: "Visa" | "Mastercard" | "Amex" | "Discover" | string;
  last4: string;
  expiry: string; // MM/YY format
  stripePaymentMethodId?: string; // For backend processing
};

export type User = {
  _id?: ObjectId; // MongoDB Object ID
  id?: string;    // Stringified ID for frontend
  name: string;
  email: string;
  password?: string; // Hashed, optional for frontend exposure
  role: "user" | "owner" | "admin";
  state?: string;
  phone?: string;
  avatarUrl?: string;

  // OAuth provider links (set when the user signs in with a social provider)
  googleId?: string;
  facebookId?: string;
  twitterId?: string;

  // Array of addresses for checkout/profile
  addresses?: Address[];

  // Basic payment info for display (actual tokens used for API)
  paymentMethods?: PaymentMethod[];

  // Stripe Customer this user's saved cards are attached to. Created lazily on
  // first checkout / card save. Saved cards live in Stripe, not this document.
  stripeCustomerId?: string;
  
  // If role === 'owner', they might be linked to a specific Store ID
  storeId?: ObjectId;

  createdAt?: Date | string;
  updatedAt?: Date | string;
};
